### PR TITLE
add latest news

### PR DESCRIPTION
**Pull request by MohAbbasher**

### CODE REVIEW

**Comment by m7mdra** [comment]
for some reasons the screen is empty. did you test it ?

**Comment by MohAbbasher** [comment]
I just modified the api URL
pls check it again

**Comment by m7mdra** [comment]
unfortunately it returns a network error.

**Comment by MohAbbasher** [comment]
it's work for me check APK :
https://drive.google.com/open?id=1GEVOztC_VK7X-CvDPx5upL4T_Z7b_GU7
check BASE_URL in ApiClient.java file it's  [   "https://**zilaapi**.000webhostapp.com/zilalapi/";      ]

**Comment by m7mdra** [comment]
good job, its working now, but there is a problem in the pagination, it dose not display all items after i go to news details screen.

**Comment by m7mdra** [comment]
good job, its working fine now.

**Pull request merged**
